### PR TITLE
Fix reference in Bower manifest.

### PR DESCRIPTION
**Pull request by watsoncj**
- fixed a typo in the main reference
- prefer non-minified nga.css as this would typically be handled further down in the asset pipeline
  - also trying to encourage devs to stop minifying their libraries in dev mode.

### CODE REVIEW

**Comment by watsoncj** [comment]
For some background. I'm using grunt-wiredep to automatically inject the dependencies into my app's index.html. Wiredep was propagating the bad reference.

Let me know if you have any issues with this patch.

**Comment by theoinglis** [comment]
Thanks @watsoncj for fixing the reference. I agree that it is probably better to use the non minified version as the resource will probably be pulled in during build and so minified later. 

Cheers for the fix

**Comment by watsoncj** [comment]
Thanks for merging this @theoinglis! 

Would you mind adding a git tag for 0.0.3? Then this would be available to import in bower via:

```
"dependencies": {
  "angular-animate-css": "0.0.3"
}
```

**Comment by theoinglis** [comment]
Done ... sorry, still getting to grips with registering bower packages. Have tested and that should be good now.

**Pull request merged**
